spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lis
    username: root
    password: s3k.Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: 0.0.0.0
    port: 1025

application:
  security:
    jwt:
      access:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 300 # 5 minutes - 86400000 # a day
      refresh:
        secret-key: 4A4E605266556A586E3272357538782F413F4428472B4B62503353672E6B5970
        expiration: 600 # - 10 min - 3600000 # 1 hour - 604800000 # 7 days
  frontend:
    default-url: boh

logging:
  #  file:
  #    path: /var/logs/
  #    file: TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO
      hibernate: INFO
